tunnel: 6dad65e6-3fcc-4c61-88c3-c7e1c3068149
credentials-file: /data/data/com.termux/files/home/.cloudflared/6dad65e6-3fcc-4c61-88c3-c7e1c3068149.json

ingress:
  - hostname: mooloomissymoo.com
    service: http://localhost:8082
  - service: http_status:404
